name: Release Docker Images (NPU)
on:
  workflow_dispatch:
    inputs:
      tag_suffix:
        description: 'tag_suffix,for example:B021,release20260203'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cann_version: ["8.5.0"]
        device_type: ["910b", "a3"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Free up disk space
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1
        with:
          tool-cache: true
          docker-images: false

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate full image tag
        run: |
          echo "FULL_TAG=cann${{ matrix.cann_version }}-${{ matrix.device_type }}-${{ github.event.inputs.tag_suffix }}" >> $GITHUB_ENV  

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: swr.cn-southwest-2.myhuaweicloud.com/base_image/dockerhub/lmsysorg/sglang
          tags: ${{ env.FULL_TAG }}

      - name: Log into docker hub
        uses: docker/login-action@v3
        if: ${{ github.repository == 'Ascend/sglang' }}
        with:
          registry: swr.cn-southwest-2.myhuaweicloud.com
          username: ${{ secrets.SWR_SOUTH_2_USERNAME }}
          password: ${{ secrets.SWR_SOUTH_2_PASSWORD }}

      # Enable Docker multi-architecture build environment
      # Emulate non-native architectures
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      # Required for building and pushing multi-arch Docker images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: docker
          file: docker/npu.Dockerfile
          platforms: linux/arm64,linux/amd64
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
          push: ${{ github.repository == 'Ascend/sglang' }}
          provenance: false
          build-args: |
            SGLANG_KERNEL_NPU_TAG=2026.01.28
            CANN_VERSION=${{ matrix.cann_version }}
            DEVICE_TYPE=${{ matrix.device_type }}